xp_config:
  model_type: BeatBockNet
  dataset: GTZAN
  ckpt_path: "./checkpoints"

data:
  path: ""
  beat_type: "tempo+beats"
  n_frames: 2048
  batch_size: 32
  valid_percent: 0.90
  n_workers: 8
  pin_memory: true

model:
  channels: 20
  kernel_size: 5
  mode: ${data.beat_type}
  dilations:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
  dropout: 0.1

optim:
  optimizer: "RAdam"
  betas:
    - 0.9
    - 0.999
  lr: 0.0003
  weight_decay: 0

trainer:
  fast_dev_run: True ####
  devices: [0]
  accelerator: "gpu"
  precision: 32
  profiler: False
  accumulate_grad_batches: 1
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 100
  max_epochs: 50000

model_checkpoint:
  dirpath: "./checkpoints"
  filename: '{epoch:02d}'
  monitor: val_loss
  every_n_epochs: 5
  save_last: true
  save_top_k: 1

callbacks:
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch

  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss/dataloader_idx_0
    min_delta: 0.0
    patience: 500